-- Ejercicios evaluables
-------------------------
--Ejercicio 1
-------------
CREATE DATABASE EJERCICIO1
GO
USE EJERCICIO1

CREATE TABLE GALERIAS(
	
	codGaleria			INT IDENTITY,
	nombre				VARCHAR (100) NOT NULL,
	ciudad				VARCHAR (100) NOT NULL,
	direccion			VARCHAR (150) NOT NULL,
	metrosCuadrados		DECIMAL (6,0) NOT NULL

	CONSTRAINT PK_GALERIAS PRIMARY KEY (codGaleria)
)



CREATE TABLE ESCUELAS(
	
	codEscuela			INT IDENTITY,
	nombre				VARCHAR (100) NOT NULL,
	pais				VARCHAR (100) NOT NULL, 
	fechaAlta			SMALLDATETIME

	CONSTRAINT PK_ESCUELAS PRIMARY KEY (codEscuela)
)

CREATE TABLE PATROCINADORES(

	codPatrocinador		INT IDENTITY,
	nombre				VARCHAR (100) NOT NULL,
	pais				VARCHAR (100) NOT NULL

	CONSTRAINT PK_PATROCINADORES PRIMARY KEY (codPatrocinador)
)

CREATE TABLE PINTORES(

	codPintor			INT IDENTITY,
	nombre				VARCHAR (100) NOT NULL,
	pais				VARCHAR (100) NOT NULL,
	codPintorMaestro	INT,
	codEscuela			INT

	CONSTRAINT PK_PINTORES PRIMARY KEY (codPintor),
	CONSTRAINT FK_PINTORES_MAESTRO FOREIGN KEY (codPintorMaestro) REFERENCES PINTORES (codPintor),
	CONSTRAINT FK_PINTORES_ESCUELA FOREIGN KEY (codEscuela) REFERENCES ESCUELAS (codEscuela)
)
GO
CREATE INDEX IX_PINTORES 
ON PINTORES (nombre)


DROP INDEX PINTORES


CREATE TABLE CUADROS (

	codCuadro			INT IDENTITY,
	dimensiones			VARCHAR (10) NOT NULL,
	fecha				SMALLDATETIME NOT NULL,
	codGaleria			INT,
	codPintor			INT,

	CONSTRAINT PK_CUADROS PRIMARY KEY (codCuadro),
	CONSTRAINT FK_CUADROS_GALERIAS FOREIGN KEY (codGaleria) REFERENCES GALERIAS (codGaleria),
	CONSTRAINT FK_CUADROS_PINTORES FOREIGN KEY (codPintor) REFERENCES PINTORES (codPintor)
)

CREATE TABLE PATROCINADORES_MECENAS(

	codPintor			INT,
	codPatrocinador		INT

	CONSTRAINT PK_PATROCINADORES_MECENAS PRIMARY KEY (codPintor, codPatrocinador),
	CONSTRAINT FK_PATROCINADORES_MECENAS_PINTORES FOREIGN KEY (codPintor) REFERENCES PINTORES (codPintor),
	CONSTRAINT FK_PATROCINADORES_MECENAS_PATROCINADORES FOREIGN KEY (codPatrocinador) REFERENCES PATROCINADORES (codPatrocinador)
)

------------------------
--Ejercicio 2
-------------

CREATE DATABASE EJERCICIO2
GO
USE EJERCICIO2

CREATE TABLE PROVINCIA (
	
	codProv				INT IDENTITY,
	nombre				CHAR (100) NOT NULL

	CONSTRAINT PK_PROVINCIA PRIMARY KEY (codProv)
)

ALTER TABLE PROVINCIA
ALTER COLUMN nombre VARCHAR (100) NOT NULL


CREATE TABLE MUNICIPIO (

	codMuni				INT IDENTITY,
	codProv				INT NOT NULL,
	nombre				CHAR (100) NOT NULL

	CONSTRAINT PK_MUNICIPIO PRIMARY KEY (codMuni, codProv),
	CONSTRAINT FK_MUNICIPIO_PROVINCIA FOREIGN KEY (codProv) REFERENCES PROVINCIA (codProv)
)

ALTER TABLE MUNICIPIO 
ALTER COLUMN nombre VARCHAR (100) NOT NULL


CREATE TABLE IMPUESTO (
	
	codImpuesto			INT IDENTITY,
	importe				DECIMAL (5,2) NOT NULL,
	fechaMaxPago		SMALLDATETIME NOT NULL,
	anyo				DECIMAL (4,0) NOT NULL,
	codMuni				INT NOT NULL,
	codProv				INT NOT NULL

	CONSTRAINT PK_IMPUESTO PRIMARY KEY (codImpuesto),
	CONSTRAINT FK_IMPUESTO_MUNICIPIO FOREIGN KEY (codMuni, codProv) REFERENCES MUNICIPIO (codMuni, codProv)
)

CREATE TABLE IBI (

	codImpuesto			INT NOT NULL,
	valCastral			DECIMAL (7,2) NOT NULL,
	tipoImpositivo		DECIMAL (7,2) NOT NULL

	CONSTRAINT PK_IBI PRIMARY KEY (codImpuesto),
	CONSTRAINT FK_IBI_IMPUESTO FOREIGN KEY (codImpuesto) REFERENCES IMPUESTO (codImpuesto)
)
GO
CREATE TABLE IVTM (
	
	codImpuesto			INT NOT NULL,
	tipoVehiculo		VARCHAR (100),
	caballosFiscales	DECIMAL (3,0),

	CONSTRAINT PK_IVTM PRIMARY KEY (codImpuesto),
	CONSTRAINT FK_IVTM_IMPUESTO FOREIGN KEY (codImpuesto) REFERENCES IMPUESTO (codImpuesto)
)
GO
CREATE TABLE IAE (

	codImpuesto			INT NOT NULL,
	factMediaAnual		DECIMAL (6,2)

	CONSTRAINT PK_IAE PRIMARY KEY (codImpuesto),
	CONSTRAINT FK_IAE_IMPUESTO FOREIGN KEY (codImpuesto) REFERENCES IMPUESTO (codImpuesto)
)

CREATE TABLE CONTRIBUYENTE (

	NIF					CHAR (9),
	nombre				VARCHAR (100) NOT NULL,
	apellido1			VARCHAR (100) NOT NULL,
	apellido2			VARCHAR (100),
	direccion			VARCHAR (150) NOT NULL,
	codPostal			DECIMAL (5,0) NOT NULL

	CONSTRAINT PK_CONTRIBUYENTE PRIMARY KEY (NIF)
)

CREATE TABLE OFICINA (
	
	codOficina			INT IDENTITY,
	nombre				VARCHAR (100) NOT NULL,
	direccion			VARCHAR (150) NOT NULL

	CONSTRAINT PK_OFICINA PRIMARY KEY (codOficina)
)

CREATE TABLE MODODEPAGO (

	codPago				CHAR (1),
	nombre				VARCHAR (20) NOT NULL,

	CONSTRAINT PK_MODODEPAGO PRIMARY KEY (codPago)
)

CREATE TABLE PAGOS (
	
	codImpuesto			INT NOT NULL,
	NIF					CHAR (9) NOT NULL,
	fechaHora			SMALLDATETIME NOT NULL,
	modoPago			CHAR (1) NOT NULL,
	codOficina			INT NOT NULL

	CONSTRAINT PK_PAGOS PRIMARY KEY (codImpuesto, NIF),
	CONSTRAINT FK_PAGOS_IMPUESTO FOREIGN KEY (codImpuesto) REFERENCES IMPUESTO (codImpuesto),
	CONSTRAINT FK_PAGOS_CONTRIBUYENTE FOREIGN KEY (NIF) REFERENCES CONTRIBUYENTE (NIF),
	CONSTRAINT FK_PAGOS_OFICINA FOREIGN KEY (codOficina) REFERENCES OFICINA (codOficina),
	CONSTRAINT FK_PAGOS_MODODEPAGO FOREIGN KEY (modoPago) REFERENCES MODODEPAGO (codPago)
)


-------------------------
--Ejercicio 3
--------------

CREATE DATABASE EJERCICIO3
GO 
USE EJERCICIO3

CREATE TABLE CATEGORIAS(

	codCategoria		INT IDENTITY,
	nombre				VARCHAR (50) NOT NULL,
	IVA					DECIMAL (2,2) NOT NULL

	CONSTRAINT PK_CATEGORIAS PRIMARY KEY (codCategoria)
)


CREATE TABLE HOTELES (

	codHotel			INT IDENTITY,
	nombre				VARCHAR (100) NOT NULL,
	direccion			VARCHAR (150) NOT NULL,
	telefono			CHAR (9) NOT NULL,
	codCategoria		INT NOT NULL

	CONSTRAINT PK_HOTELES PRIMARY KEY (codHotel),
	CONSTRAINT FK_HOTELES_CATEGORIAS FOREIGN KEY (codCategoria) REFERENCES CATEGORIAS (codCategoria)
)

ALTER TABLE CATEGORIAS 
ALTER COLUMN IVA DECIMAL (4,2) NOT NULL

CREATE TABLE HABITACIONES (

	codHotel			INT NOT NULL,
	codHabitacion		INT IDENTITY,
	tipoHabitacion		VARCHAR (50) NOT NULL,
	precio				DECIMAL (5,2) NOT NULL

	CONSTRAINT PK_HABITACIONES PRIMARY KEY (codHotel, codHabitacion),
	CONSTRAINT FK_HABITACIONES_HOTELES FOREIGN KEY (codHotel) REFERENCES HOTELES (codHotel) 
)




CREATE TABLE CLIENTES (
	
	codCliente			INT IDENTITY,
	nombre				VARCHAR (100) NOT NULL,
	direccion			VARCHAR (150) NOT NULL,
	telefono			CHAR (9) NOT NULL

	CONSTRAINT PK_CLIENTES PRIMARY KEY (codCliente)
)


CREATE TABLE PARTICULARES (

	codCliente			INT NOT NULL,
	DNI					CHAR (9) NOT NULL

	CONSTRAINT PK_PARTICULARES PRIMARY KEY (codCliente),
	CONSTRAINT FK_PARTICULARES_CLIENTES FOREIGN KEY (codCliente) REFERENCES CLIENTES (codCliente)
)


CREATE TABLE AGENCIAS (
	
	codCliente			INT NOT NULL,
	nombreAgencia		VARCHAR (100)

	CONSTRAINT PK_AGENCIAS PRIMARY KEY (codCliente),
	CONSTRAINT FK_AGENCIAS_CLIENTES FOREIGN KEY (codCliente) REFERENCES CLIENTES (codCliente)
)

CREATE TABLE RESERVAS (
	
	codReserva			INT IDENTITY,
	codHotel			INT NOT NULL,
	codHabitacion		INT NOT NULL,
	codCliente			INT NOT NULL,
	fechaInicio			SMALLDATETIME NOT NULL,
	fechaFin			SMALLDATETIME NOT NULL,
	precioTotal			DECIMAL (6,2) NOT NULL

	CONSTRAINT PK_RESERVAS PRIMARY KEY (codReserva),
	CONSTRAINT FK_RESERVAS_HABITACIONES FOREIGN KEY (codHotel, codHabitacion) REFERENCES HABITACIONES (codHotel, codHabitacion),
	CONSTRAINT FK_RESERVA_CLIENTE FOREIGN KEY (codCliente) REFERENCES CLIENTES (codCliente)
)

