--Ejercicio1
CREATE DATABASE PRUEBA
GO
USE PRUEBA

DROP TABLE GALERIAS

CREATE TABLE GALERIAS(
codGaleria		INT IDENTITY (1,1),
nombre			VARCHAR(100) NOT NULL,
ciudad			VARCHAR(100) NOT NULL,
direccion		VARCHAR(100) NOT NULL,
metrosCuadrados	INT

CONSTRAINT PK_GALERIAS PRIMARY KEY (codGaleria)
)

CREATE TABLE ESCUELAS(
codEscuela		INT IDENTITY(1,1),
nombre			VARCHAR(100) NOT NULL,
pais			VARCHAR(100) NOT NULL,
fechaAlta		DATE NOT NULL,

CONSTRAINT PK_ESCUELAS PRIMARY KEY (codEscuela)
)



CREATE TABLE PATROCINADORES(
codPatrocinador	INT IDENTITY(1,1),
nombre			VARCHAR(100) NOT NULL,
pais			VARCHAR(100) NOT NULL

CONSTRAINT PK_PATROCINADORES PRIMARY KEY (codPatrocinador)
)


CREATE TABLE PINTORES(
codPintor			INT IDENTITY(1,1),
nombre				VARCHAR(100) NOT NULL,
pais				VARCHAR(100) NOT NULL,
codPintorMaestro	INT NOT NULL,
codEscuela			INT NOT NULL

CONSTRAINT PK_PINTORES PRIMARY KEY (codPintor),
CONSTRAINT FK_PINTORES_ESCUELAS FOREIGN KEY (codEscuela) REFERENCES ESCUELAS (codEscuela)
)

ALTER TABLE PINTORES
ADD CONSTRAINT FK_PINTORES_PINTORMAESTRO FOREIGN KEY (codPintorMaestro) REFERENCES PINTORES (codPintor)



CREATE TABLE CUADROS(
codCuadro		INT IDENTITY (1,1),
dimensiones		INT NOT NULL,
fecha			DATE NOT NULL,
tecnica			VARCHAR(100) NOT NULL,
codGaleria		INT NOT NULL,
codPintor		INT NOT NULL

CONSTRAINT PK_CUADROS PRIMARY KEY (codCuadro),
CONSTRAINT FK_CUADROS_GALERIAS FOREIGN KEY (codGaleria) REFERENCES GALERIAS (codGaleria),
CONSTRAINT FK_CUADROS_PINTORES FOREIGN KEY (codPintor) REFERENCES PINTORES (codPintor)
)

CREATE TABLE PATROCINADORES_MECENAS(
codPintor		INT NOT NULL,
codPatrocinador	INT NOT NULL

CONSTRAINT FK_PATROCINADORES_MECENAS_PINTORES FOREIGN KEY (codPintor) REFERENCES PINTORES (codPintor),
CONSTRAINT FK_PATROCINADORES_MECENAS_PATROCINADORES FOREIGN KEY (codPatrocinador) REFERENCES PATROCINADORES (codPatrocinador)
)
----------------------------------------------------------------------------------------------
--Ejercicio2

CREATE DATABASE PRUEBA2
GO 
USE PRUEBA2


CREATE TABLE PROVINCIA(
codProv			INT IDENTITY(1,1),
nombre			VARCHAR(100) NOT NULL

CONSTRAINT PK_PROVINCIA PRIMARY KEY (codProv)
)

CREATE TABLE MUNICIPIO(
codMuni			INT IDENTITY(1,1),
nombre			VARCHAR(100) NOT NULL,
codProv			INT NOT NULL,

CONSTRAINT PK_MUNICIPIO PRIMARY KEY (codMuni, codProv),
CONSTRAINT FK_MUNICIPIO_PROVINCIA FOREIGN KEY (codProv) REFERENCES PROVINCIA (codProv)
)

CREATE TABLE IMPUESTO(
codImpuesto		INT IDENTITY(1,1),
importe			DECIMAL(5,2) NOT NULL,
fechaMaxPago	DATE NOT NULL,
codProv			INT NOT NULL,
codMuni			INT NOT NULL

CONSTRAINT PK_IMPUESTO PRIMARY KEY (codImpuesto),
CONSTRAINT FK_IMPUESTO_MUNICIPIO FOREIGN KEY (codMuni, codProv) REFERENCES MUNICIPIO (codMuni, codProv)
)

CREATE TABLE IMPUESTO_IBI(
codImpuesto			INT NOT NULL,
valCatastral		DECIMAL(5,2) NOT NULL,
tipoImpositivo		DECIMAL(5,2) NOT NULL

CONSTRAINT PK_IMPUESTO_IBI PRIMARY KEY (codImpuesto),
CONSTRAINT FK_IMPUESTO_IBI_IMPUESTO FOREIGN KEY (codImpuesto) REFERENCES IMPUESTO (codImpuesto)
)

CREATE TABLE IMPUESTO_IVTM(
codImpuesto			INT NOT NULL,
tipoVehiculo		VARCHAR(50) NOT NULL,
caballosFiscales	DECIMAL(3,0) NOT NULL

CONSTRAINT PK_IMPUESTO_IVTM PRIMARY KEY (codImpuesto),
CONSTRAINT FK_IMPUESTO_IVTM_IMPUESTO FOREIGN KEY (codImpuesto) REFERENCES IMPUESTO (codImpuesto)
)

CREATE TABLE IMPUESTO_IAE(
codImpuesto		INT NOT NULL,
factMediaAnual	DECIMAL(6,2) NOT NULL

CONSTRAINT PK_IMPUESTO_IAE PRIMARY KEY (codImpuesto),
CONSTRAINT FK_IMPUESTO_IAE_IMPUESTO FOREIGN KEY (codImpuesto) REFERENCES IMPUESTO (codImpuesto)
)


--------------------------------------------------------------------------------------------
--Ejercicio3
CREATE DATABASE PRUEBA3
GO
USE PRUEBA3

CREATE TABLE CATEGORIAS(
codCategoria		INT IDENTITY,
nombre				VARCHAR(100) NOT NULL,
IVA					DECIMAL(4,2)

CONSTRAINT PK_CATEGORIAS PRIMARY KEY (codCategoria)
)

CREATE TABLE HOTELES(
codHotel			INT IDENTITY,
nombre				VARCHAR(100) NOT NULL,
direccion			VARCHAR(100) NOT NULL,
telefono			CHAR(9) NOT NULL,
codCategoria		INT NOT NULL

CONSTRAINT PK_HOTELES PRIMARY KEY (codHotel),
CONSTRAINT FK_HOTELES_CATEGORIAS FOREIGN KEY (codCategoria) REFERENCES CATEGORIAS (codCategoria)
)

CREATE TABLE HABITACIONES(
codHotel			INT NOT NULL,
codHabitacion		INT NOT NULL,
tipoHabitacion		VARCHAR(50) NOT NULL,
precio				DECIMAL(6,2) NOT NULL

CONSTRAINT PK_HABITACIONES PRIMARY KEY (codHotel, codHabitacion),
CONSTRAINT FK_HABITACIONES_HOTELES FOREIGN KEY (codHotel) REFERENCES HOTELES (codHotel)
)

CREATE TABLE CLIENTES(
codCliente			INT IDENTITY,
nombre				VARCHAR(100) NOT NULL,
direccion			VARCHAR(100) NOT NULL,
telefono			CHAR(9) NOT NULL

CONSTRAINT PK_CLIENTES PRIMARY KEY (codCliente)
)

CREATE TABLE PARTICULARES(
codCliente			INT,
DNI					CHAR(9) NOT NULL

CONSTRAINT PK_CLIENTES_PARTICULARES PRIMARY KEY (codCliente),
CONSTRAINT FK_CLIENTES_PARTICULARES_CLIENTES FOREIGN KEY (codCliente) REFERENCES CLIENTES (codCliente)
)

CREATE TABLE AGENCIAS(
codCliente			INT,
nombreAgencia		VARCHAR(100)

CONSTRAINT PK_CLIENTES_AGENCIAS PRIMARY KEY (codCliente),
CONSTRAINT FK_CLIENTES_AGENCIAS_CLIENTES FOREIGN KEY (codCliente) REFERENCES CLIENTES (codCliente)
)

CREATE TABLE RESERVAS(
codReserva			INT,
codHotel			INT NOT NULL,
codHabitacion		INT NOT NULL,
codCliente			INT NOT NULL,
fechaInicio			SMALLDATETIME,
fechaFin			SMALLDATETIME,
precioTotal			DECIMAL(8,2)

CONSTRAINT PK_RESERVAS	PRIMARY KEY (codReserva),
CONSTRAINT FK_RESERVAS_HABITACIONES FOREIGN KEY (codHotel, codHabitacion) REFERENCES HABITACIONES (codHotel, codHabitacion),
CONSTRAINT FK_RESERVAS_CLIENTES FOREIGN KEY (codCliente) REFERENCES CLIENTES (codCliente)
)

-----------------------------------------------
--ELIMINAR BASES DE DATOS
DROP DATABASE PRUEBA